import datetime


TO_NUMBER = lambda n: float(n)


def TO_DATE(s):
    # Check number of hypens to understand formatting: 0 >> just year, 1 >> year-month, 2 >> year-month-day
    if s.count("-") == 2:
        return datetime.datetime.strptime(s, "%Y-%m-%d")
    if s.count("-") == 1:
        return datetime.datetime.strptime(s, "%Y-%m")
    if s.count("-") == 0:
        return datetime.datetime.strptime(s, "%Y")


def asset_schema():
    """
    Return validation schema for ASSETS data type.
    """
    schema = {
        "AN1": {
            "type": "datetime",
            "coerce": TO_DATE,
            "min": datetime.datetime(2012, 1, 1, 0, 0),
            "max": datetime.datetime(2030, 12, 31, 0, 0),
            "meta": {"label": "Pool Cut-off Date"},
        },
        "AN2": {"type": "string", "meta": {"label": "Pool Identifier"}},
        "AN3": {"type": "string", "meta": {"label": "Servicer Name"}},
        "AN4": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Backup Servicer Name"},
        },
        "AN5": {"type": "string", "meta": {"label": "Loan Identifier"}},
        "AN6": {"type": "string", "nullable": True, "meta": {"label": "Originator"}},
        "AN7": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Regulated Loan"},
        },
        "AN8": {
            "type": "string",
            "meta": {"label": "Borrower Identifier"},
        },
        "AN10": {
            "type": "string",
            "meta": {"label": "Loan Currency Denomination"},
        },
        "AN11": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Total Credit Limit"},
        },
        "AN12": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Revolving End Date - Loan"},
        },
        "AN15": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Borrower Credit Quality"},
        },
        "AN16": {
            "type": "string",
            "allowed": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
            "nullable": True,
            "meta": {"label": "Borrower's Employment Status"},
        },
        "AN17": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Primary Income"},
        },
        "AN18": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Primary Income Currency"},
        },
        "AN19": {
            "type": "string",
            "allowed": ["0", "1", "2", "3", "4", "5", "6"],
            "nullable": True,
            "meta": {"label": "Income Verification for Primary Income"},
        },
        "AN20": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Geographic Region"},
        },
        "AN21": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Origination Date"},
        },
        "AN22": {
            "type": "datetime",
            "coerce": TO_DATE,
            "nullable": True,
            "meta": {"label": "Expected Loan Maturity"},
        },
        "AN23": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Original Loan Term"},
        },
        "AN24": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Pool Addition Date"},
        },
        "AN25": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Original Principal Balance"},
        },
        "AN26": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Current Principal Outstanding Balance"},
        },
        "AN27": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Scheduled Payment Due"},
        },
        "AN28": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6", "7", "8"],
            "nullable": True,
            "meta": {"label": "Scheduled Payment Frequency"},
        },
        "AN29": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5"],
            "nullable": True,
            "meta": {"label": "Repayment Method"},
        },
        "AN30": {
            "type": "string",
            "allowed": [
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
            ],
            "nullable": True,
            "meta": {"label": "Loan Purpose"},
        },
        "AN31": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Interest Rate Reset Interval"},
        },
        "AN32": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Current Interest Rate"},
        },
        "AN33": {
            "type": "string",
            "allowed": [
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
            ],
            "nullable": True,
            "meta": {"label": "Current Interest Rate Basis"},
        },
        "AN34": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Current Interest Rate Margin"},
        },
        "AN35": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Number of Borrowers"},
        },
        "AN36": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Percentage of Prepayments allowed"},
        },
        "AN37": {
            "type": "number",
            "coerce": TO_NUMBER,
            "nullable": True,
            "min": 0.0,
            "meta": {"label": "Early Repayment Charges"},
        },
        "AN38": {
            "type": "string",
            "allowed": ["1", "2", "3"],
            "nullable": True,
            "meta": {"label": "Customer Type"},
        },
        "AN39": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6", "7", "8"],
            "nullable": True,
            "meta": {"label": "Origination Channel"},
        },
        "AN40": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6"],
            "nullable": True,
            "meta": {"label": "Payment Method"},
        },
        "AN41": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Date Removed from the Pool"},
        },
        "AN42": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Deposit Amount"},
        },
        "AN43": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Employee"},
        },
        "AN44": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Interest Cap Rate"},
        },
        "AN45": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Interest Floor Rate"},
        },
        "AN49": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Arrears Balance"},
        },
        "AN50": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Number of Months in Arrears"},
        },
        "AN51": {
            "type": "datetime",
            "coerce": TO_DATE,
            "min": datetime.datetime(2012, 1, 1),
            "nullable": True,
            "meta": {"label": "Default Date"},
        },
        "AN52": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Gross Default Amount"},
        },
        "AN55": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Cumulative Recoveries"},
        },
        "AN56": {
            "type": "datetime",
            "coerce": TO_DATE,
            "min": datetime.datetime(2012, 1, 1),
            "nullable": True,
            "meta": {"label": "Redemption Date"},
        },
        "AN58": {
            "type": "string",
            "allowed": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
            "nullable": True,
            "meta": {"label": "Account Status"},
        },
        "AN59": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Arrears Balance Capitalised"},
        },
        "AN60": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Date of Most Recent Arrears Capitalisation"},
        },
        "AN61": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Loan Ever in Arrears"},
        },
    }
    return schema


def bond_info_schema():
    """
    Return validation schema for BOND_INFO data type.
    """
    schema = {
        "BN1": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "meta": {"label": "Report Date"},
        },
        "BN2": {"type": "string", "meta": {"label": "Issuer"}},
        "BN4": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "All Reserve Accounts at Target Balance"},
        },
        "BN5": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Drawings under Liquidity Facility"},
        },
        "BN11": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Excess Spread Amount"},
        },
        "BN12": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Trigger Measurements/Ratios"},
        },
        "BN13": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Annualised Constant Prepayment Rate"},
        },
        "BN14": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Excess Spread %"},
        },
        "BN15": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Total Receivables Sold to SPV"},
        },
        "BN16": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Cumulative Gross Defaults - Pool"},
        },
        "BN17": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Cumulative Recoveries - Pool"},
        },
        "BN18": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Revolving Period End Date"},
        },
        "BN19": {
            "type": "string",
            "meta": {"label": "Point Contact"},
        },
        "BN20": {"type": "string", "meta": {"label": "Contact Information"}},
        "BN25": {
            "type": "string",
            "meta": {"label": "Bond Class Name"},
        },
        "BN26": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "International Securities Identification Number"},
        },
        "BN27": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Interest Payment Date"},
        },
        "BN28": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Principal Payment Date"},
        },
        "BN29": {
            "type": "string",
            "meta": {"label": "Bond Currency"},
        },
        "BN30": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Original Principal Balance"},
        },
        "BN31": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Total Ending Balance Subsequent to Payment"},
        },
        "BN32": {
            "type": "string",
            "allowed": [
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
            ],
            "nullable": True,
            "meta": {"label": "Reference Rate"},
        },
        "BN33": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Relevant Margin"},
        },
        "BN34": {
            "type": "number",
            "coerce": TO_NUMBER,
            "nullable": True,
            "meta": {"label": "Coupon Reference Rate"},
        },
        "BN35": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Current Coupon"},
        },
        "BN36": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Cumulative Interest Shortfall "},
        },
        "BN37": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Cumulative Principal Shortfalls"},
        },
        "BN38": {
            "type": "datetime",
            "coerce": TO_DATE,
            "min": datetime.datetime(2012, 1, 1, 0, 0),
            "meta": {"label": "Legal Maturity"},
        },
        "BN39": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "meta": {"label": "Bond Issue Date"},
        },
        "BN40": {
            "type": "datetime",
            "coerce": TO_DATE,
            "nullable": True,
            "meta": {"label": "Scheduled Maturity Date"},
        },
        "BN41": {
            "type": "string",
            "allowed": ["0", "1", "2", "3", "4", "5"],
            "nullable": True,
            "meta": {"label": "Interest Payment Frequency"},
        },
        "BN42": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Step-Up Date"},
        },
        "BN43": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Step-Up Rate"},
        },
        "BN44": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Initial Credit Enhancement in percentage terms"},
        },
        "BN45": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Current Credit Enhancement in percentage terms"},
        },
        "BN46": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "FX Swap Rate"},
        },
    }
    return schema
