"""
ingest_bronze.py — Bronze/Silver Ingestion into DuckDB
=======================================================
Reads the synthetic Parquet files generated by the data designer and loads
them into the local credit_validate.db DuckDB database.

Static loan origination attributes -> static_loans table
Dynamic monthly performance cutoffs -> dynamic_performance table

Usage:
    python ingest_bronze.py [--db PATH] [--data-dir PATH]
"""

import argparse
import json
import os
import sys
import time
from pathlib import Path

import duckdb
import pandas as pd

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
WORKSPACE_DIR = Path(__file__).parent
SCHEMA_SQL    = WORKSPACE_DIR / "db_schema.sql"
DEFAULT_DB    = WORKSPACE_DIR / "credit_validate.db"
DEFAULT_DATA  =  WORKSPACE_DIR.parent.parent.parent / "deep-loans" / "synthetic-data-designer" / "out_10k"

# ---------------------------------------------------------------------------
# Column definitions: which columns from the Parquet go to which table
# ---------------------------------------------------------------------------

STATIC_COLS = [
    "loan_id", "origination_year", "original_balance", "legal_maturity_months",
    "repayment_type", "interest_only_flag", "rate_type",
    "interest_payment_frequency", "principal_payment_frequency",
    "borrower_type", "debtor_count", "loan_part_count",
    "employment_status", "self_employed_flag",
    "loan_purpose", "buy_to_let_flag",
    "borrower_annual_income", "loan_to_income", "payment_due_to_income_pct",
    "scheduled_monthly_payment",
    "property_type", "province", "economic_region_nuts3", "country",
    "construction_year", "occupancy", "property_usage",
    "original_market_value_at_origination", "property_valuation_type",
    "oltomv_original",
    "nhg_flag", "guarantee_type",
    "epc_label", "epc_issue_year", "primary_energy_demand_kwh_m2",
    "construction_deposit_flag", "construction_deposit_pct",
    "construction_deposit_amount",
    "transaction_name", "esma_transaction_identifier",
    "originator_name", "servicer_name", "currency",
    "closing_date", "maturity_date_proxy",
]

DYNAMIC_COLS = [
    "loan_id", "reporting_date",
    "current_balance", "current_interest_rate_pct",
    "remaining_interest_fixed_period_months",
    "fixed_interest_period_end_in_months",
    "remaining_term_months", "seasoning_months",
    "cltomv_current", "cltimv_current",
    "current_original_market_value", "indexed_market_value",
    "arrears_bucket", "arrears_amount", "days_past_due",
    "default_crr_flag", "performing_status",
    "foreclosure_flag", "forbearance_flag", "restructuring_flag",
    "balance_bucket", "cltomv_current_bucket", "cltimv_current_bucket",
    "oltomv_original_bucket", "loan_to_income_bucket",
    "payment_due_to_income_pct_bucket", "construction_year_bucket",
]


def connect_db(db_path: Path) -> duckdb.DuckDBPyConnection:
    """Create or connect to a DuckDB file."""
    return duckdb.connect(str(db_path))


def init_schema(con: duckdb.DuckDBPyConnection, schema_path: Path) -> None:
    """Execute the DDL schema script."""
    print(f"  Initializing schema from {schema_path.name} ...")
    sql = schema_path.read_text(encoding="utf-8")
    con.executemany("", [])   # noop to flush
    con.execute(sql)
    print("  OK Schema initialized")


def load_static_loans(con: duckdb.DuckDBPyConnection, data_dir: Path) -> int:
    """
    Load static origination data from loan_book.parquet into static_loans.
    We take only the first row per loan_id to get the origination-time values.
    """
    parquet_path = data_dir / "loan_book.parquet"
    print(f"\n  Loading static_loans from {parquet_path.name} ...")
    t0 = time.perf_counter()

    # Use DuckDB's native Parquet reader — fastest possible load path
    # Deduplicate: keep first occurrence per loan_id (origination snapshot)
    cols = ", ".join(
        f'"{c}"' if c in ("default_crr_flag", "buy_to_let_flag",
                           "interest_only_flag", "nhg_flag", "self_employed_flag",
                           "foreclosure_flag", "forbearance_flag",
                           "restructuring_flag", "construction_deposit_flag") else f'"{c}"'
        for c in STATIC_COLS
    )

    # Build a safe column list (only columns that exist in the parquet)
    df_sample = pd.read_parquet(parquet_path, columns=None).head(1)
    available = set(df_sample.columns)
    safe_static = [c for c in STATIC_COLS if c in available]

    insert_sql = f"""
    INSERT INTO static_loans
    SELECT DISTINCT ON (loan_id) {', '.join(f'"{c}"' for c in safe_static)}
    FROM read_parquet('{parquet_path.as_posix()}')
    ORDER BY loan_id, reporting_date
    """
    con.execute(insert_sql)
    count = con.execute("SELECT COUNT(*) FROM static_loans").fetchone()[0]
    elapsed = time.perf_counter() - t0
    print(f"  OK static_loans: {count:,} rows loaded in {elapsed:.2f}s")
    return count


def load_dynamic_performance(con: duckdb.DuckDBPyConnection, data_dir: Path) -> int:
    """
    Load all monthly cutoff data from all_cutoffs.parquet into dynamic_performance.
    """
    parquet_path = data_dir / "all_cutoffs.parquet"
    print(f"\n  Loading dynamic_performance from {parquet_path.name} ...")
    t0 = time.perf_counter()

    # Check which dynamic columns are available
    df_sample = pd.read_parquet(parquet_path, columns=None).head(1)
    available = set(df_sample.columns)
    safe_dynamic = [c for c in DYNAMIC_COLS if c in available]

    insert_sql = f"""
    INSERT INTO dynamic_performance
    SELECT {', '.join(f'"{c}"' for c in safe_dynamic)}
    FROM read_parquet('{parquet_path.as_posix()}')
    """
    con.execute(insert_sql)
    count = con.execute("SELECT COUNT(*) FROM dynamic_performance").fetchone()[0]
    elapsed = time.perf_counter() - t0
    print(f"  OK dynamic_performance: {count:,} rows loaded in {elapsed:.2f}s")
    return count


def profile_bronze(con: duckdb.DuckDBPyConnection) -> dict:
    """Run basic bronze-level profiling checks."""
    print("\n  Running Bronze profiling checks ...")
    report = {}

    # PK uniqueness: (loan_id, reporting_date) should be unique
    dup_count = con.execute("""
        SELECT COUNT(*) FROM (
            SELECT loan_id, reporting_date, COUNT(*) AS cnt
            FROM dynamic_performance
            GROUP BY loan_id, reporting_date
            HAVING cnt > 1
        )
    """).fetchone()[0]
    report["duplicate_loan_date_pairs"] = dup_count
    print(f"    Duplicate (loan_id, reporting_date) pairs: {dup_count}")

    # NULL check on critical columns
    null_checks = {
        "static_loans.loan_id_nulls":          "SELECT COUNT(*) FROM static_loans WHERE loan_id IS NULL",
        "static_loans.original_balance_nulls": "SELECT COUNT(*) FROM static_loans WHERE original_balance IS NULL",
        "dynamic.loan_id_nulls":               "SELECT COUNT(*) FROM dynamic_performance WHERE loan_id IS NULL",
        "dynamic.reporting_date_nulls":        "SELECT COUNT(*) FROM dynamic_performance WHERE reporting_date IS NULL",
        "dynamic.current_balance_nulls":       "SELECT COUNT(*) FROM dynamic_performance WHERE current_balance IS NULL",
    }
    for name, sql in null_checks.items():
        val = con.execute(sql).fetchone()[0]
        report[name] = val
        status = "OK" if val == 0 else "[WARNING]"
        print(f"    {status} {name}: {val}")

    # Row counts per reporting_date (verify 24 months)
    cutoff_count = con.execute(
        "SELECT COUNT(DISTINCT reporting_date) FROM dynamic_performance"
    ).fetchone()[0]
    report["distinct_reporting_dates"] = cutoff_count
    print(f"    Distinct reporting_dates: {cutoff_count} (expected ~24)")

    # Unique loan count
    unique_loans = con.execute(
        "SELECT COUNT(DISTINCT loan_id) FROM static_loans"
    ).fetchone()[0]
    report["unique_loans"] = unique_loans
    print(f"    Unique loans: {unique_loans:,}")

    return report


def get_db_stats(con: duckdb.DuckDBPyConnection) -> dict:
    """Retrieve final DB statistics."""
    stats = {}
    for tbl in ["static_loans", "dynamic_performance"]:
        cnt = con.execute(f"SELECT COUNT(*) FROM {tbl}").fetchone()[0]
        stats[tbl] = cnt

    gold_cnt = con.execute("SELECT COUNT(*) FROM gold_features").fetchone()[0]
    stats["gold_features"] = gold_cnt
    return stats


def main():
    parser = argparse.ArgumentParser(description="CFM Bronze/Silver Ingestion")
    parser.add_argument("--db",       type=Path, default=DEFAULT_DB,
                        help="Path to DuckDB database file")
    parser.add_argument("--data-dir", type=Path, default=DEFAULT_DATA,
                        help="Directory containing loan_book.parquet and all_cutoffs.parquet")
    args = parser.parse_args()

    print("=" * 60)
    print("  Credit Foundation Model — Bronze/Silver Ingestion")
    print("=" * 60)
    print(f"  Database : {args.db}")
    print(f"  Data Dir : {args.data_dir}")

    # Delete existing DB to ensure a clean load
    if args.db.exists():
        args.db.unlink()
        print(f"\n  Removed existing database: {args.db.name}")

    t_total = time.perf_counter()

    con = connect_db(args.db)
    init_schema(con, SCHEMA_SQL)

    static_count  = load_static_loans(con, args.data_dir)
    dynamic_count = load_dynamic_performance(con, args.data_dir)
    profile       = profile_bronze(con)
    db_stats      = get_db_stats(con)
    con.close()

    total_elapsed = time.perf_counter() - t_total

    print("\n" + "=" * 60)
    print("  Ingestion Complete")
    print("=" * 60)
    print(f"  static_loans       : {db_stats['static_loans']:>10,} rows")
    print(f"  dynamic_performance: {db_stats['dynamic_performance']:>10,} rows")
    print(f"  gold_features view : {db_stats['gold_features']:>10,} rows (ML-ready)")
    print(f"  Total time         : {total_elapsed:.2f}s")

    # Save report
    report = {
        "database": str(args.db),
        "static_loans_loaded":       static_count,
        "dynamic_performance_loaded": dynamic_count,
        "gold_features_rows":        db_stats["gold_features"],
        "bronze_profile":            profile,
        "total_seconds":             round(total_elapsed, 3),
        "status":                    "ok" if profile.get("duplicate_loan_date_pairs", 1) == 0 else "warnings",
    }
    report_path = WORKSPACE_DIR / "ingest_report.json"
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(f"\n  Report saved -> {report_path.name}")

    return 0 if report["status"] == "ok" else 1


if __name__ == "__main__":
    sys.exit(main())
